[package]
name = "logtower-parser"
version = "1.0.0"
authors = ["NeonShapeshifter"]
edition = "2021"

[dependencies]
evtx = "0.8.1"
serde_json = "1.0"
clap = { version = "4.4", features = ["derive"] }
anyhow = "1.0"
rayon = "1.8"